name: MCP Conformance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mcp-spec-tester fastmcp
        pip install -e .
        
    - name: Start MCP server
      run: |
        python -m mcp_reflect.server &
        sleep 5 # Give server time to start
        
    - name: Run MCP conformance tests
      run: |
        mcp-spec-tester --url http://localhost:8080
