name: release

on:
  workflow_run:
    workflows: ["tests"]
    branches: [main]
    types: [completed]

permissions:
  contents: write # Für Release-Erstellung und Tag-Push
  pull-requests: write # Für PR-Erstellung/-Update
  id-token: write # Für PyPI Trusted Publishing

jobs:
  semrel:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    concurrency: release # verhindert parallele Releases
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Version, Tag & GitHub-Release
        id: semrel
        uses: python-semantic-release/python-semantic-release@v9
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optionaler PyPI-Upload via Trusted Publishing
      - name: Upload to PyPI (OIDC)
        # if: ${{ steps.semrel.outputs.released == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
